name: Publish Python distribution to PyPI and TestPyPI
# Source:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build distribution package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '>=0.7'
      - name: Add untagged version suffix
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        run: uvx pyverno update django_cte/__init__.py
      - name: Build a binary wheel and a source tarball
        run: uv build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  version-check:
    name: Check for version match in git tag and django_cte.__version__
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '>=0.7'
      - name: Check version
        run: uvx pyverno check django_cte/__init__.py "${{ github.ref }}"
  pypi-publish:
    name: Upload release to PyPI
    needs: [build, version-check]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-cte
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  pypi-test-publish:
    name: Upload release to test PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/django-cte
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
